version: '3'
services:
  hugo:
    container_name: hugo
    image: dceoy/hugo
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - /opt/go/bin/hugo
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts
      - --watch
